script: make test
sudo: true
trusty: true
language: python
python:
  - "2.7"
install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-7
  - env -u CFLAGS -u LDFLAGS pip install -r test/requirements.txt
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-multilib
      - libcap-dev
env:
  - CFLAGS=-m64 LDFLAGS=-m64 CC=gcc-7
